image: "python:2.7-slim"

before_script:
  - python -v

test:
  script:
  - pip install nose==1.3.7 coverage==4.2
  - pip install -r requirements.txt
  - nosetests --with-coverage --cover-package=equake --cover-xml
